### ISSUE TITLE
프로젝트중 개인공부

### ISSUE THREAD

**Issue by inthej** [inthej/ThinkNote#3]
[Java의 정석]
- abstract 의미 : 미완성
 WindowAdapter 클래스 : 객체생성못하게 abstract 쓰기도 하지만 class 생성해봐야 할수 있는게 아무것도 없다. 이럴때도 abstract를 사용해서 표현한다. 구현안된 빈 껍데기 메서드로 구성. WindowListener 필요한것만 오버라이딩 해서 주면 된다. 
객체 생성을 못하는데 사용할 수 있는 이유는 이름없는 MouseAdapter class 를 상속하는 이름없는 익명 클래스를 생성하기 때문이다.
 new MouseAdapter() {  };
---
- interface 사용되는 변수는 static 상수이다. : static 상수는 보통 표현을 위해.. 클래스 쩜 으로 사용되고 이러한 표현으로 interface의 다중상속의 충돌도 예방할수 있다. 

- 메서드의 리턴타입이 인터페이스라는 것은 메서드가 해당 인터페이스를 구현한 클래스의 인스턴스를 반환한다는 것을 의미한다. 

- interface의 default method 의 default는 접근제어자가 아니다. default 메서드 사용은 다중상속 때문에 충돌 우려가 있음. 규칙은 있지만 오버라이딩 사용 권장한다. 

- instance inner class 에서의 맴버 변수의 static사용은 상수(final)만 가능하다. (final static 상수) 

- static Inner class 의 객체 생성 
class A { 	
  static class Inner { } 
  static Inner inner = new Inner();
 }

- method 안에서 지역클래스 선언이 가능하다.
void myMethod() { 	
  class LocalInner { 	} 
}

---
[리팩토링(Refactoring)]
- Vector의 add()와 addElement() 메서드
이 두 method는 완전히 동일한 기능을 한다.
add() 사용이 일반적 JDK 1.2에서 추가
addElement()는 Vector에만 존재하는 API이다
add메서드는 메서드 실행 성공여부를 boolean값으로 리턴하지만
addElement는 별도의 리턴값이 없다.
---
- abstract class : 내가 구현해도되고 자식보고 구현하라고해도된다.
---
- 다형성을 사용하면 @Override기법으로 if~else 를 피할수 있다. 
class Movie {
  private Price _price; (실제데이터)
  int getFrequentRenterPoints(int daysRented) {
    return _price.getFrequentRenterPoints(daysRented);
  }
}
class Price {
  int getFrequentRenterPoints(int daysRented) {
    return 1;
  }
}
class NewReleasePrice extends Price {
  @Override
  int getFrequentRenterPoints(int daysRented) {
    return (daysRented > 1) ? 2 : 1;
  }
}
---
-

**Comment by inthej** [comment]
* abstract 의미 : 미완성 WindowAdapter 클래스 : 객체생성못하게 abstract 쓰기도 하지만 class 생성해봐야 할수 있는게 아무것도 없다. 이럴때도 abstract를 사용해서 표현한다. 구현안된 빈 껍데기 메서드로 구성. WindowListener 필요한것만 오버라이딩 해서 주면 된다. 
* 객체 생성을 못하는데 사용할 수 있는 이유는 이름없는 MouseAdapter class 를 상속하는 이름없는 클래스를 생성하는것이기 때문이다. new MouseAdapter() { 
};
* interface 사용되는 변수는 static 상수이다. : static 상수는 보통 표현을 위해.. 클래스 쩜 으로 사용되고 이러한 표현으로 interface의 다중상속의 충돌도 예방할수 있다. 
* 메서드의 리턴타입이 인터페이스라는 것은 메서드가 해당 인터페이스를 구현한 클래스의 인스턴스를 반환한다는 것을 의미한다. 
* interface의 default method 의 default는 접근제어자가 아니다. default 메서드 사용은 다중상속 때문에 충돌 우려가 있음. 규칙은 있지만 오버라이딩 사용 권장한다. 
* instance inner class 에서의 맴버 변수의 static사용은 상수(final)만 가능하다. (final static 상수) 
* static Inner class 의 객체 생성 
class A { 	static class Inner { }
	static Inner inner = new Inner(); }
* method 안에서 지역클래스 선언이 가능하다.
void myMethod() { 	class LocalInner { 	} }

**Comment by Mommoo** [comment]
for루프 처리 메서드 Naming
ex) amountFor() { } 이런식 처리하는 듯 하다.

검증 된건가요... 생각 없이 받아 드리는게 제일 위험하다 했습니다.
진짜 저 이름을 보고 뭐하는건지 알 수 있습니까?
ex) 총합을 구하는건지, 요소마다 추가, 삭제 하는건지 의미를 알 수 있어요?

**Comment by inthej** [comment]
아네. 말씀들어보니 안좋은 표현으로 보여집니다.
평소 'for 문 메서드는 어떻게 표현할까?' 생각을 갖고 있었고 그러던 와중에 저런 걸 보게 되어서 그리 느꼈던 거 같습니다.
어떻게 처리하느냐가 아니라. 어떤행위를 하느냐가 더 중요한 거였군요
무슨말인지 이해했습니다. 조언 감사합니다.
